GET http://localhost:8080/api/theater/audition HTTP/1.1

###

GET  http://localhost:8080/api/theater/audition/1 HTTP/1.1


###
GET http://localhost:8080/api/theater/auditionee HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjYXBzdG9uZS1iYWNrZW5kIiwic3ViIjoiYWRtaW4iLCJhdXRob3JpdGllcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2NTUyMzQ3ODh9.P5OJpypdrbol-_Lj_fbdmjxCSmdDYa4V7tqvxL_EEPc

###
POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "user",
    "password": "user"
}

###
POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
POST http://localhost:8080/api/theater/audition HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjYXBzdG9uZS1iYWNrZW5kIiwic3ViIjoiYWRtaW4iLCJhdXRob3JpdGllcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2NTUzMDQyNDF9.HMosL5uG8_p9XBk2yx-4SeQsmggJTBoEOVVdSolpxPo

{
  "auditioneeId": 3,
  "partId": 2
}

###
POST http://localhost:8080/api/theater/auditionee