GET http://localhost:8080/api/theater/audition HTTP/1.1

###

GET  http://localhost:8080/api/theater/person HTTP/1.1


###
GET http://localhost:8080/api/theater/auditionee HTTP/1.1

###

POST http://localhost:8080/create_account HTTP/1.1
Content-Type: application/json

{
  "username": "cCody",
  "password": "password1!"
}

###

POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
  "username": "cCody",
  "password": "password1!"
}

###

POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "user",
    "password": "user"
}

###
POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
POST http://localhost:8080/api/theater/audition HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjYXBzdG9uZS1iYWNrZW5kIiwic3ViIjoiZW1tYXpnIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2NTU5NTYzNDh9.RB8Xf69mXRlTDC2ikftQg7OcxP4AtLtXUut3FF0i9y8

{
  "auditioneeId": 2,
  "partId": 1
}

###
POST http://localhost:8080/api/theater/auditionee

###

#begin auditionee requests

# should deny access because we don't have admin authority yet
GET http://localhost:8080/api/theater/auditionee HTTP/1.1

###

# gets a token for admin privileges
POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
# uses the ADMIN token privilege to READ auditionees
GET http://localhost:8080/api/theater/auditionee/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjYXBzdG9uZS1iYWNrZW5kIiwic3ViIjoiY0dlbm5hcm8iLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsImV4cCI6MTY1NTU3OTQ0NX0.VrO6D-9nyTpdqaAZKqb4T7bQtXkRM8RbJ5hC0XXmudA

###

# gets a token for user privileges
POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "msmith",
    "password": "password1!"
}

###

# should deny access to auditionee list because this is user privileges only
GET http://localhost:8080/api/theater/auditionee HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjYXBzdG9uZS1iYWNrZW5kIiwic3ViIjoibXNtaXRoIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2NTU3NDI0NDR9.avg-1V26mSj2byfwzZ4pwIVaaR4fM6lZFO_A6Iem8BI
###

# uses the USER privileges to ADD an auditionee
POST http://localhost:8080/api/theater/auditionee HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjYXBzdG9uZS1iYWNrZW5kIiwic3ViIjoiZW1tYXpnIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE2NTU5NTYzNDh9.RB8Xf69mXRlTDC2ikftQg7OcxP4AtLtXUut3FF0i9y8

{
    "appUserId": 3,
    "partId": 1,
    "timeSlot": "2022-07-01 9:00am",
    "selection": "Song 1"
}

###

# uses ADMIN privileges to UPDATE an auditionee
# should return 204 with no content
PUT http://localhost:8080/api/theater/auditionee/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjYXBzdG9uZS1iYWNrZW5kIiwic3ViIjoiZ29vZCIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjU2MDExMjk5fQ.pNJYsN-o1rpXSHAJd7ktC8vzttgoNOoI6fosWiqFU9g

{
    "auditioneeId": 1,
    "appUserId": 3,
    "partId": 2,
    "timeSlot": "2022-07-01 5:00pm",
    "selection": "Kristin Monologue"
}

###

# uses ADMIN privileges to DELETE auditioneeId 3
# should return 204 with no content
DELETE http://localhost:8080/api/theater/auditionee/2 HTTP/1.1
